@startuml
'https://plantuml.com/activity-diagram-beta

partition "**Check Move Validity Diagram**"

<style>
activityDiagram {
  BackgroundColor #FFF8DC
  BorderColor #FFFFFF

  diamond {
    BackgroundColor #FFE4C4
  }
}
</style>

start
#FFE4AA:Start;
#FFE4AA:Check reachability of the destination square;
if () then (The destination is one square away)
    if () then ([The destination is River square])
        if (Check piece's type) then ([The moving piece is Rat])
            label cont1
            if (Check the state of destination square) then ([Not occupied])
                else ([Occupied])
                    if (Check pieces' rank) then ([The moving side has a superior rank])
                    else ([The moving side has an inferior rank])])
                        #FFE4AA:Output [Invalid Move];
                        stop
                    endif
             endif
        else ([The moving piece is not Rat])
            #FFE4AA:Output [Invalid Move];
            stop
        endif
    else ([The destination is not River square])])
        label cont2
        goto cont1
    endif
else (The destination is two or more squares away)
    if (Check piece's type) then ([The moving piece is Lion or Tiger])
        if (Check the path) then ([There are river squares on the path and no rat is on the path])
            label cont3
            goto cont2
        else ([There is no river square on the path or any rat is in the river square on the path])
            #FFE4AA:Output [Invalid Move];
            stop
        endif
    else ([The moving piece is neither Lion or Tiger])
        #FFE4AA:Output [Invalid Move];
        stop
    endif
endif

#FFE4AA:Output [Valid Move];

stop

@enduml
